name: "SIMCSE"
init:
    _target_: models.get_VCO2_models.SIMCSE
    checkpoint: "princeton-nlp/sup-simcse-bert-base-uncased"
    
tokenizer:
    _target_: transformers.AutoTokenizer.from_pretrained
    pretrained_model_name_or_path: ${..init.checkpoint}
params:
    padding: True
    truncation: True
    return_tensors: "pt"

     

