name: "MMFusion"
init:
    _target_: models.get_VCO2_models.MMFusion
    encoders : ???  
    fusion : ???
    classifier:  ???
collator: 
    init:
        _target_: datasets.MMClassificationCollator
        text_feature_extractors: ???
        image_processing: ???
criterion: 
    _target_: torch.nn.CrossEntropyLoss
optimizer: 
    _target_: torch.optim.Adam
    lr: 1e-4