wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.10
    start_time: 1683061408.004571
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 33
      - 41
      - 49
      - 50
      - 51
      - 53
      - 54
      - 55
      - 75
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 33
      - 41
      - 49
      - 50
      - 51
      - 53
      - 54
      - 55
      - 75
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.13.10
      6: 4.26.1
      8:
      - 8
batch_size:
  desc: null
  value: 32
dataset:
  desc: null
  value: eorigin_full_multimodalDataset.csv
fusion_method:
  desc: null
  value: Custom Concat
fusion_params:
  desc: null
  value: '{''_target_'': ''models.commun_fusion.CustomConcat'', ''hidden_dim'': 500,
    ''num_modalities'': 2}'
hs_level:
  desc: null
  value: 2
image_column:
  desc: null
  value: image_name
initial_learning_rate:
  desc: null
  value: 0.0001
min_value:
  desc: null
  value: 50
model_name:
  desc: null
  value: SIMCSE_princeton-nlp/sup-simcse-bert-base-uncased_textcol_Invoice_description_VGG16_Custom
    Concat
num_classes:
  desc: null
  value: 33
seed:
  desc: null
  value: 70
test size:
  desc: null
  value: 1952
text_columns:
  desc: null
  value:
  - Invoice_description
train size:
  desc: null
  value: 18912
train_test_size:
  desc: null
  value: 0.1
train_val_size:
  desc: null
  value: 0.11
val size:
  desc: null
  value: 2368
