defaults:
    - dataset: VCO2_dataset 
    - model: model1
    - text_encoder: simcse
    - image_encoder: vgg16
    - fusion: customconcat
    - classifier: mlp

fast_dev_run: True
wandb:
  project: "VCO2"
  
output_folder: "output_runs_VCO2/"
batch_size: 32
epochs: 1
seed: 70